# Generated by Django 4.2.4 on 2023-08-18 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=150)),
                ('blog_post', models.TextField()),
                ('blog_author', models.CharField(max_length=30)),
                ('date_published', models.DateTimeField(verbose_name=datetime.datetime(2023, 8, 18, 10, 49, 43, 923753, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
