# Generated by Django 4.2.4 on 2023-08-18 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_blog_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 18, 14, 10, 44, 673223, tzinfo=datetime.timezone.utc)),
        ),
    ]
